name: "github-actions"

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: print a dummy text
        run: echo "Hello World"
      - name: log node and npm version
        run: |
          node -v
          npm -v
          npx -v
  run-on-different-shells:
    runs-on: ubuntu-latest
    steps:
      - name: use bash shell
        run: echo "Hello World"
      - name: use python shell
        run: |
          google = "I'm Google play with me"
          print(google);
        shell: python
