name: checkout-action

on: [pull_request]

jobs:
  clone-repo-and-log-contents:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo and checkout to master
        uses: "actions/checkout@v2"
      - name: log the contents
        run: ls -a
